spring:
  application:
    name: front
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/test?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接时的最大等待时间
      max-wait: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计
      filters: stat,wall,slf4j
      # 检测连接是否有效的 SQL语句，为空时以下三个配置均无效
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
      test-on-return: true
      # 申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效，默认false，建议开启，不影响性能
      test-while-idle: true
      use-global-data-source-stat: true
      filter:
        slf4j:
          enabled: true
          connection-log-enabled: false
          result-set-log-enabled: false
          statement-log-enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-parameter-set-log-enabled: false
          statement-prepare-after-log-enabled: false
          statement-executable-sql-log-enable: false
          statement-execute-update-after-log-enabled: true
          statement-execute-query-after-log-enabled: true
          statement-close-after-log-enabled: false
          connection-close-after-log-enabled: false
        stat:
          enabled: true
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 30000


eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  client:
    serviceUrl:
      defaultZone: http://192.168.1.5:8761/eureka/


mybatis:
  type-handlers-package: org.example.front.mapper.handler
  configuration:
    cache-enabled: true
    default-fetch-size: 100
    default-statement-timeout: 30
    default-enum-type-handler: org.example.front.mapper.EnumHandler
    default-sql-provider-type: org.example.front.mapper.SqlProvider
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: debug
    druid.sql.Statement: debug

server:
  port: 8081

